local prequire = require 'eprader.prequire'
prequire 'eprader.colorscheme'
prequire 'eprader.notify'
-- INFO: Load `colorscheme` and `notify` first so that it applies to all following `prequire`.
prequire 'eprader.settings'
prequire 'eprader.keymaps'
prequire 'eprader.lsp'
prequire 'eprader.telescope'
prequire 'eprader.treesitter'
prequire 'eprader.lsp'
prequire 'eprader.dressing'
prequire 'eprader.cmp'
prequire 'eprader.harpoon'
prequire 'eprader.autopairs'
prequire 'eprader.gitsigns'
prequire 'eprader.dap'
prequire 'eprader.dapui'
prequire 'eprader.lualine'
prequire 'eprader.nvim-r'
prequire 'eprader.java'
prequire 'eprader.trouble'
prequire 'eprader.todo-comments'
prequire 'eprader.comment'
prequire 'eprader.toggleterm'
prequire 'eprader.overseer'
